In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
data = 'Depr.csv'

df = pd.read_csv(data, header=None)

In [4]:
df.shape

(186, 13)

In [5]:
df.head()

0   1       2   3    4       5   6     7               8    9   10   11  \
0  18  70    Good   8  Yes  Single   3  Good              No   No  No   No   
1  18  60  Normal  10  Yes  Single   3  Good              No   No  No   No   
2  19  70    Good   8  Yes  Single   4  Good             Yes  Yes  No   No   
3  19  50  Normal   6  Yes  Single   2  Good              No  Yes  No  Yes   
4  18  90    Good  10  Yes  Single   2  Good  Not applicable  Yes  No   No   

    12  
0  Yes  
1  Yes  
2  Yes  
3   No  
4  Yes

In [6]:
col_names = ['age', 'scale', 'feeling', 'sleep', 'finance', 'relation', 'adjustment','understanding','result','living','inferiority','sick','recreation']


df.columns = col_names

col_names

['age',
 'scale',
 'feeling',
 'sleep',
 'finance',
 'relation',
 'adjustment',
 'understanding',
 'result',
 'living',
 'inferiority',
 'sick',
 'recreation']

In [7]:
df.head()

age  scale feeling  sleep finance relation  adjustment understanding  \
0   18     70    Good      8     Yes   Single           3          Good   
1   18     60  Normal     10     Yes   Single           3          Good   
2   19     70    Good      8     Yes   Single           4          Good   
3   19     50  Normal      6     Yes   Single           2          Good   
4   18     90    Good     10     Yes   Single           2          Good   

           result living inferiority sick recreation  
0              No     No          No   No        Yes  
1              No     No          No   No        Yes  
2             Yes    Yes          No   No        Yes  
3              No    Yes          No  Yes         No  
4  Not applicable    Yes          No   No        Yes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 13 columns):
age              186 non-null int64
scale            186 non-null int64
feeling          186 non-null object
sleep            186 non-null int64
finance          186 non-null object
relation         186 non-null object
adjustment       186 non-null int64
understanding    186 non-null object
result           186 non-null object
living           186 non-null object
inferiority      186 non-null object
sick             186 non-null object
recreation       186 non-null object
dtypes: int64(4), object(9)
memory usage: 19.0+ KB


In [9]:
col_names = ['age', 'scale', 'feeling', 'sleep', 'finance', 'relation', 'adjustment','understanding','result','living','inferiority','sick','recreation']

for col in col_names:
    print(df[col].value_counts())

20    50
21    47
19    42
22    34
18     7
23     6
Name: age, dtype: int64
30     18
10     15
70     14
55     13
45     12
5      12
75     11
85     11
25     11
15     11
50     10
90     10
65      9
95      9
35      9
100     8
80      2
60      1
Name: scale, dtype: int64
Very bad     38
Bad          38
Very good    37
Good         37
Normal       36
Name: feeling, dtype: int64
6     47
8     30
3     20
2     19
7     18
5     17
4     16
1     14
10     5
Name: sleep, dtype: int64
Yes    108
No      78
Name: finance, dtype: int64
Single               64
In a relationship    45
Broken Up            33
It's complicated     28
Married              16
Name: relation, dtype: int64
1    42
5    37
3    37
2    36
4    34
Name: adjustment, dtype: int64
Good      76
Bad       67
Normal    43
Name: understanding, dtype: int64
No                88
Yes               85
Not applicable    13
Name: result, dtype: int64
Yes               97
No                84
Not applicable     5
Name:

In [10]:
df['feeling'].value_counts()

Very bad     38
Bad          38
Very good    37
Good         37
Normal       36
Name: feeling, dtype: int64

In [11]:
df.isnull().sum()

age              0
scale            0
feeling          0
sleep            0
finance          0
relation         0
adjustment       0
understanding    0
result           0
living           0
inferiority      0
sick             0
recreation       0
dtype: int64

In [12]:
X = df.drop(['feeling'], axis=1)

y = df['feeling']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [14]:
X_train.shape, X_test.shape

((148, 12), (38, 12))

In [15]:
X_train.dtypes

age               int64
scale             int64
sleep             int64
finance          object
relation         object
adjustment        int64
understanding    object
result           object
living           object
inferiority      object
sick             object
recreation       object
dtype: object

In [16]:
X_train.head()

age  scale  sleep finance           relation  adjustment understanding  \
123   19     45      5      No  In a relationship           3        Normal   
135   22     10      1      No   It's complicated           1           Bad   
150   20     30      3      No             Single           2           Bad   
31    22     85      7     Yes  In a relationship           5        Normal   
12    21     85      8     Yes             Single           5          Good   

    result living inferiority sick recreation  
123     No    Yes          No   No        Yes  
135     No     No         Yes  Yes         No  
150     No     No         Yes   No         No  
31     Yes    Yes          No   No        Yes  
12     Yes    Yes          No   No         No

In [17]:
!pip install category-encoders
import category_encoders as ce

In [18]:
encoder = ce.OrdinalEncoder(cols=['finance', 'relation', 'understanding', 'result', 'living', 'inferiority','sick','recreation'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [19]:
X_train.head()

age  scale  sleep  finance  relation  adjustment  understanding  result  \
123   19     45      5        1         1           3              1       1   
135   22     10      1        1         2           1              2       1   
150   20     30      3        1         3           2              2       1   
31    22     85      7        2         1           5              1       2   
12    21     85      8        2         3           5              3       2   

     living  inferiority  sick  recreation  
123       1            1     1           1  
135       2            2     2           2  
150       2            2     1           2  
31        1            1     1           1  
12        1            1     1           2

In [20]:
encodery = ce.OrdinalEncoder(cols=['feeling'])

y_train = encodery.fit_transform(y_train)
y_test = encodery.transform(y_test)

In [21]:
y_train.head(20)

feeling
123        1
135        2
150        3
31         4
12         4
41         1
51         4
56         3
93         1
90         5
66         2
38         2
55         5
98         1
153        3
96         4
2          5
112        3
46         3
65         4

In [22]:
X_test.head()

age  scale  sleep  finance  relation  adjustment  understanding  result  \
113   20     10      1        1         1           1              2       1   
164   20     75      6        2         1           4              3       2   
169   21     55      5        1         1           3              1       2   
101   18     85      6        2         3           5              3       2   
100   19     30      4        1         2           2              2       1   

     living  inferiority  sick  recreation  
113       2            2     2           2  
164       1            1     1           1  
169       2            1     1           1  
101       1            1     1           1  
100       2            2     2           2

In [23]:
from sklearn.naive_bayes import GaussianNB

In [24]:
classifier= GaussianNB()

In [25]:
classifier.fit(X_train, y_train)  

GaussianNB(priors=None, var_smoothing=1e-09)

In [26]:
y_pred= classifier.predict(X_test)  

In [27]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [28]:
y_pred

array([2, 5, 1, 4, 3, 1, 4, 3, 3, 2, 5, 3, 1, 2, 3, 5, 1, 4, 3, 4, 3, 3,
       4, 5, 3, 3, 5, 5, 3, 4, 4, 3, 4, 1, 3, 2, 2, 1])

In [29]:
X_test.head(10)

age  scale  sleep  finance  relation  adjustment  understanding  result  \
113   20     10      1        1         1           1              2       1   
164   20     75      6        2         1           4              3       2   
169   21     55      5        1         1           3              1       2   
101   18     85      6        2         3           5              3       2   
100   19     30      4        1         2           2              2       1   
15    22     55      8        2         3           3              1       2   
177   19     85      8        2         3           5              3       2   
35    22     25      4        2         4           2              1       3   
119   20     30      3        1         1           2              2       1   
152   22      5      1        1         1           1              2       1   

     living  inferiority  sick  recreation  
113       2            2     2           2  
164       1            1     1           1  
169       2            1     1           1  
101       1            1     1           1  
100       2            2     2           2  
15        1            1     1           2  
177       1            1     1           1  
35        2            2     2           2  
119       2            2     2           2  
152       2            2     2           2

In [30]:
y_test.head(10)

feeling
113        2
164        5
169        1
101        4
100        3
15         1
177        4
35         3
119        3
152        2

In [31]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion entropy: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with criterion entropy: 1.0000


In [32]:
y_pred_train = classifier.predict(X_train)

y_pred_train

array([1, 2, 3, 4, 4, 1, 4, 3, 1, 5, 2, 2, 5, 1, 3, 4, 5, 3, 3, 4, 4, 3,
       4, 1, 5, 1, 5, 3, 1, 3, 5, 1, 5, 5, 4, 3, 2, 1, 3, 5, 2, 5, 3, 2,
       4, 1, 2, 3, 5, 2, 2, 1, 5, 3, 2, 4, 1, 3, 1, 4, 2, 2, 5, 1, 1, 4,
       2, 1, 2, 5, 2, 5, 3, 4, 1, 5, 5, 4, 5, 4, 3, 2, 5, 3, 5, 1, 3, 2,
       2, 4, 3, 1, 4, 1, 5, 4, 2, 5, 2, 4, 2, 4, 5, 4, 1, 5, 2, 3, 1, 3,
       2, 1, 4, 5, 3, 4, 4, 2, 2, 4, 5, 1, 1, 5, 3, 4, 2, 1, 2, 5, 2, 1,
       4, 4, 5, 3, 5, 2, 4, 1, 1, 1, 2, 2, 2, 2, 2, 5])

In [33]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.9797


In [34]:
print('Training set score: {:.4f}'.format(classifier.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(classifier.score(X_test, y_test)))

Training set score: 0.9797
Test set score: 1.0000


In [35]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[ 6  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0 13  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0  6]]


In [36]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         6
           2       1.00      1.00      1.00         5
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         6

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

