In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
data = 'Dep.csv'

df = pd.read_csv(data, header=None)

In [4]:
df.shape

(101, 13)

In [5]:
df.head()

0   1       2   3    4       5   6     7               8    9   10   11  \
0  18  70    Good   8  Yes  Single   3  Good              No   No  No   No   
1  18  60  Normal  10  Yes  Single   3  Good              No   No  No   No   
2  19  70    Good   8  Yes  Single   4  Good             Yes  Yes  No   No   
3  19  50  Normal   6  Yes  Single   2  Good              No  Yes  No  Yes   
4  18  90    Good  10  Yes  Single   2  Good  Not applicable  Yes  No   No   

    12  
0  Yes  
1  Yes  
2  Yes  
3   No  
4  Yes

In [6]:
col_names = ['age', 'scale', 'feeling', 'sleep', 'finance', 'relation', 'adjustment','understanding','result','living','inferiority','sick','recreation']


df.columns = col_names

col_names

['age',
 'scale',
 'feeling',
 'sleep',
 'finance',
 'relation',
 'adjustment',
 'understanding',
 'result',
 'living',
 'inferiority',
 'sick',
 'recreation']

In [7]:
df.head()

age  scale feeling  sleep finance relation  adjustment understanding  \
0   18     70    Good      8     Yes   Single           3          Good   
1   18     60  Normal     10     Yes   Single           3          Good   
2   19     70    Good      8     Yes   Single           4          Good   
3   19     50  Normal      6     Yes   Single           2          Good   
4   18     90    Good     10     Yes   Single           2          Good   

           result living inferiority sick recreation  
0              No     No          No   No        Yes  
1              No     No          No   No        Yes  
2             Yes    Yes          No   No        Yes  
3              No    Yes          No  Yes         No  
4  Not applicable    Yes          No   No        Yes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 13 columns):
age              101 non-null int64
scale            101 non-null int64
feeling          101 non-null object
sleep            101 non-null int64
finance          101 non-null object
relation         101 non-null object
adjustment       101 non-null int64
understanding    101 non-null object
result           101 non-null object
living           101 non-null object
inferiority      101 non-null object
sick             101 non-null object
recreation       101 non-null object
dtypes: int64(4), object(9)
memory usage: 10.3+ KB


In [9]:
col_names = ['age', 'scale', 'feeling', 'sleep', 'finance', 'relation', 'adjustment','understanding','result','living','inferiority','sick','recreation']

for col in col_names:
    print(df[col].value_counts())

21    28
22    25
19    19
20    17
23     6
18     6
Name: age, dtype: int64
30     11
55      8
90      7
10      7
15      7
70      7
95      6
50      6
5       6
65      5
45      5
35      5
75      5
25      5
85      5
100     3
80      2
60      1
Name: scale, dtype: int64
Bad          21
Good         20
Very bad     20
Normal       20
Very good    20
Name: feeling, dtype: int64
6     21
8     19
7     15
4     15
2      9
5      7
3      7
10     5
1      3
Name: sleep, dtype: int64
Yes    65
No     36
Name: finance, dtype: int64
Single               33
In a relationship    21
It's complicated     18
Broken Up            15
Married              14
Name: relation, dtype: int64
1    24
5    20
3    20
2    19
4    18
Name: adjustment, dtype: int64
Good      41
Bad       32
Normal    28
Name: understanding, dtype: int64
No                46
Yes               42
Not applicable    13
Name: result, dtype: int64
Yes               56
No                40
Not applicable     5
Name: l

In [10]:
df['feeling'].value_counts()

Bad          21
Good         20
Very bad     20
Normal       20
Very good    20
Name: feeling, dtype: int64

In [11]:
df.isnull().sum()

age              0
scale            0
feeling          0
sleep            0
finance          0
relation         0
adjustment       0
understanding    0
result           0
living           0
inferiority      0
sick             0
recreation       0
dtype: int64

In [12]:
X = df.drop(['feeling'], axis=1)

y = df['feeling']

age  scale  sleep finance           relation  adjustment understanding  \
0     18     70      8     Yes             Single           3          Good   
1     18     60     10     Yes             Single           3          Good   
2     19     70      8     Yes             Single           4          Good   
3     19     50      6     Yes             Single           2          Good   
4     18     90     10     Yes             Single           2          Good   
5     18     25      4     Yes             Single           1        Normal   
6     18     10      5     Yes             Single           1        Normal   
7     19     90      8     Yes             Single           5          Good   
8     20     65     10     Yes             Single           4          Good   
9     19     30      7     Yes             Single           2          Good   
10    18     65     10     Yes             Single           3        Normal   
11    21     80      8     Yes             Single           4          Good   
12    21     85      8     Yes             Single           5          Good   
13    21     95     10     Yes             Single           5          Good   
14    21      5      4      No             Single           1        Normal   
15    22     55      8     Yes             Single           3        Normal   
16    19     80      8     Yes             Single           4          Good   
17    20     30      4      No  In a relationship           2           Bad   
18    21     35      5      No          Broken Up           2           Bad   
19    22     95      8     Yes  In a relationship           5          Good   
20    22     55      6     Yes             Single           3          Good   
21    19     55      8     Yes  In a relationship           3        Normal   
22    20     35      3      No          Broken Up           2        Normal   
23    19     10      5     Yes             Single           1        Normal   
24    22     75      8     Yes             Single           4        Normal   
25    19     15      3     Yes             Single           1        Normal   
26    19     45      8     Yes             Single           3        Normal   
27    20     50      7      No   It's complicated           4        Normal   
28    21     50      7     Yes  In a relationship           3        Normal   
29    21     55      6     Yes  In a relationship           3        Normal   
..   ...    ...    ...     ...                ...         ...           ...   
71    19     15      2      No             Single           1           Bad   
72    20     55      6     Yes   It's complicated           3        Normal   
73    21     85      7     Yes  In a relationship           5          Good   
74    23     90      7     Yes             Single           5          Good   
75    23     25      4      No            Married           2           Bad   
76    19     30      3      No             Single           2           Bad   
77    20     75      6     Yes  In a relationship           4          Good   
78    21     45      6     Yes  In a relationship           3        Normal   
79    22     50      7     Yes   It's complicated           3        Normal   
80    21     55      6     Yes            Married           3        Normal   
81    22     50      5      No   It's complicated           3        Normal   
82    22     70      7     Yes            Married           4          Good   
83    21     15      2      No          Broken Up           1           Bad   
84    21     95      7     Yes   It's complicated           5          Good   
85    21     10      1      No          Broken Up           1           Bad   
86    22      5      2     Yes          Broken Up           1           Bad   
87    21     15      2      No  In a relationship           1           Bad   
88    22     70      8     Yes            Married           4          Good   
89    23    100      8     Yes            Married      

In [13]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [14]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((80, 12), (21, 12))

In [15]:
# check data types in X_train

X_train.dtypes

age               int64
scale             int64
sleep             int64
finance          object
relation         object
adjustment        int64
understanding    object
result           object
living           object
inferiority      object
sick             object
recreation       object
dtype: object

In [16]:
X_train.head()

age  scale  sleep finance relation  adjustment understanding  \
89   23    100      8     Yes  Married           5          Good   
26   19     45      8     Yes   Single           3        Normal   
42   22     95      8     Yes  Married           5          Good   
70   21     45      6     Yes   Single           3        Normal   
15   22     55      8     Yes   Single           3        Normal   

            result living inferiority sick recreation  
89             Yes    Yes          No   No        Yes  
26  Not applicable     No       Maybe   No        Yes  
42             Yes    Yes          No   No        Yes  
70             Yes     No          No   No        Yes  
15             Yes    Yes          No   No         No

In [17]:
# import category encoders
!pip install category-encoders
import category_encoders as ce

In [18]:
# encode variables with ordinal encoding

encoder = ce.OrdinalEncoder(cols=['finance', 'relation', 'understanding', 'result', 'living', 'inferiority','sick','recreation'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [19]:
X_train.head()

age  scale  sleep  finance  relation  adjustment  understanding  result  \
89   23    100      8        1         1           5              1       1   
26   19     45      8        1         2           3              2       2   
42   22     95      8        1         1           5              1       1   
70   21     45      6        1         2           3              2       1   
15   22     55      8        1         2           3              2       1   

    living  inferiority  sick  recreation  
89       1            1     1           1  
26       2            2     1           1  
42       1            1     1           1  
70       2            1     1           1  
15       1            1     1           2

In [20]:
encodery = ce.OrdinalEncoder(cols=['feeling'])

y_train = encodery.fit_transform(y_train)
y_test = encodery.transform(y_test)

In [21]:
y_train.head(20)

feeling
89        1
26        2
42        1
70        2
15        2
40        3
72        2
9         3
96        1
11        4
91        4
64        3
28        2
83        5
5         3
47        3
53        5
35        3
16        4
81        2

In [22]:


X_test.head()



age  scale  sleep  finance  relation  adjustment  understanding  result  \
84   21     95      7        1         3           5              1       1   
55   19     65      6        1         4           4              1       2   
66   22     10      1        2         5           1              3       3   
67   22     15      2        2         4           1              3       3   
45   20     35      5        1         2           1              3       3   

    living  inferiority  sick  recreation  
84       1            1     1           2  
55       1            1     1           1  
66       2            3     1           2  
67       2            3     2           2  
45       2            2     1           2

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
classifier= RandomForestClassifier(n_estimators=10,criterion="entropy")

In [25]:
classifier.fit(X_train, y_train)  

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [26]:
y_pred= classifier.predict(X_test)  

In [27]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  

In [28]:
y_pred

array([1, 4, 5, 5, 5, 5, 3, 5, 4, 2, 3, 1, 4, 4, 4, 4, 2, 2, 1, 1, 3])

In [29]:
X_test.head(10)

age  scale  sleep  finance  relation  adjustment  understanding  result  \
84   21     95      7        1         3           5              1       1   
55   19     65      6        1         4           4              1       2   
66   22     10      1        2         5           1              3       3   
67   22     15      2        2         4           1              3       3   
45   20     35      5        1         2           1              3       3   
39   22      5      3        1         5           1              3       3   
22   20     35      3        2         5           2              2       2   
44   21      5      4        2         1           1              3       2   
10   18     65     10        1         2           3              2       1   
0    18     70      8        1         2           3              1       3   

    living  inferiority  sick  recreation  
84       1            1     1           2  
55       1            1     1           1  
66       2            3     1           2  
67       2            3     2           2  
45       2            2     1           2  
39       2            3     2           2  
22       2            3     2           2  
44       2            3     2           2  
10       1            1     1           1  
0        2            1     1           1

In [30]:
y_test.head(10)

feeling
84        1
55        4
66        5
67        5
45        3
39        5
22        3
44        5
10        4
0         4

In [31]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion entropy: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))


Model accuracy score with criterion entropy: 0.9048


In [32]:
y_pred_train = classifier.predict(X_train)

y_pred_train

array([1, 2, 1, 2, 2, 3, 2, 3, 1, 4, 4, 3, 2, 5, 3, 3, 5, 3, 4, 2, 4, 1,
       1, 1, 2, 1, 1, 5, 4, 1, 1, 4, 2, 3, 5, 4, 2, 5, 1, 3, 4, 3, 3, 3,
       1, 3, 3, 3, 4, 2, 2, 2, 5, 1, 4, 2, 3, 5, 3, 2, 4, 5, 5, 2, 2, 5,
       2, 4, 5, 5, 3, 1, 5, 4, 2, 1, 5, 5, 5, 1])

In [33]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 1.0000


In [34]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(classifier.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(classifier.score(X_test, y_test)))

Training set score: 1.0000
Test set score: 0.9048


In [35]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)


Confusion matrix

 [[4 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 1]
 [0 1 0 6 0]
 [0 0 0 0 4]]


In [36]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         4
           2       0.67      1.00      0.80         2
           3       1.00      0.75      0.86         4
           4       1.00      0.86      0.92         7
           5       0.80      1.00      0.89         4

    accuracy                           0.90        21
   macro avg       0.89      0.92      0.89        21
weighted avg       0.93      0.90      0.91        21

